
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WordWebServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WordWebServiceSoap {


    /**
     * 
     * @param ndid
     * @param stoken
     * @param nid
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "http://tempuri.org/getWordByFatherId")
    @WebResult(name = "getWordByFatherIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getWordByFatherId", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWordByFatherId")
    @ResponseWrapper(localName = "getWordByFatherIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWordByFatherIdResponse")
    public byte[] getWordByFatherId(
        @WebParam(name = "ndid", targetNamespace = "http://tempuri.org/")
        int ndid,
        @WebParam(name = "stoken", targetNamespace = "http://tempuri.org/")
        String stoken,
        @WebParam(name = "nid", targetNamespace = "http://tempuri.org/")
        int nid);

    /**
     * 
     * @param ndid
     * @param noffice
     * @param stoken
     * @param nhid
     * @param ntype
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "http://tempuri.org/getWordByNtypeAndOfficeUniDoctor")
    @WebResult(name = "getWordByNtypeAndOfficeUniDoctorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getWordByNtypeAndOfficeUniDoctor", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWordByNtypeAndOfficeUniDoctor")
    @ResponseWrapper(localName = "getWordByNtypeAndOfficeUniDoctorResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWordByNtypeAndOfficeUniDoctorResponse")
    public byte[] getWordByNtypeAndOfficeUniDoctor(
        @WebParam(name = "ndid", targetNamespace = "http://tempuri.org/")
        int ndid,
        @WebParam(name = "stoken", targetNamespace = "http://tempuri.org/")
        String stoken,
        @WebParam(name = "ntype", targetNamespace = "http://tempuri.org/")
        int ntype,
        @WebParam(name = "nhid", targetNamespace = "http://tempuri.org/")
        int nhid,
        @WebParam(name = "noffice", targetNamespace = "http://tempuri.org/")
        int noffice);

}
