
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WordWebService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://103.244.232.251:8080/ImageCloudServicePlatformService/webService/clinic/WordWebService.asmx?wsdl")
public class WordWebService
    extends Service
{

    private final static URL WORDWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException WORDWEBSERVICE_EXCEPTION;
    private final static QName WORDWEBSERVICE_QNAME = new QName("http://tempuri.org/", "WordWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://103.244.232.251:8080/ImageCloudServicePlatformService/webService/clinic/WordWebService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WORDWEBSERVICE_WSDL_LOCATION = url;
        WORDWEBSERVICE_EXCEPTION = e;
    }

    public WordWebService() {
        super(__getWsdlLocation(), WORDWEBSERVICE_QNAME);
    }

    public WordWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WORDWEBSERVICE_QNAME, features);
    }

    public WordWebService(URL wsdlLocation) {
        super(wsdlLocation, WORDWEBSERVICE_QNAME);
    }

    public WordWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WORDWEBSERVICE_QNAME, features);
    }

    public WordWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WordWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WordWebServiceSoap
     */
    @WebEndpoint(name = "WordWebServiceSoap")
    public WordWebServiceSoap getWordWebServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "WordWebServiceSoap"), WordWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WordWebServiceSoap
     */
    @WebEndpoint(name = "WordWebServiceSoap")
    public WordWebServiceSoap getWordWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WordWebServiceSoap"), WordWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WORDWEBSERVICE_EXCEPTION!= null) {
            throw WORDWEBSERVICE_EXCEPTION;
        }
        return WORDWEBSERVICE_WSDL_LOCATION;
    }

}
